source 'https://rubygems.org'

# For faster file watcher updates on Windows:
# gem 'wdm', :platforms => [:mswin, :mingw]

gem 'middleman-presentation', '~> 0.16.0.rc1'

# Choose one to make `execjs` happy
# gem 'therubyracer'
# gem 'therubyrhino'

gem 'kramdown'
gem 'github-markup'
gem 'liquid'
gem 'rake'

group :debug do
  gem 'pry'
  gem 'byebug'
  gem 'pry-byebug'
end
